// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N11_SellerAPI.Models;

public partial class Store
{
    public long Id { get; set; }

    public string StoreLink { get; set; }

    public string StoreName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Mersis { get; set; }

    public string Category { get; set; }

    public decimal? StoreScore { get; set; }

    public int? RatingCount { get; set; }

    public decimal? RatingScore { get; set; }

    public int? ProductCount { get; set; }

    public string SellerName { get; set; }

    public bool? Send { get; set; }

    public bool? Checked { get; set; }
}